---
- name: 0.系统初始化
  gather_facts: false
  hosts: newnode 
  roles:
    - common
  tags: common 

- name: 2.部署Contanerd
  gather_facts: false
  hosts: newnode  
  roles:
    - containerd
  tags: containerd

- name: 2.部署K8S Node
  gather_facts: false
  hosts: newnode
  roles:
    - node
  tags: node
